### ISSUE TITLE
Selecting presets crashes Lightroom with tangent-lightroom enabled

### ISSUE THREAD

**Issue by malzzz** [crazyscot/tangent-lightroom#2]
If I have tangent-lightroom enabled, scrubbing through presets crashes Lightroom almost 100% of the time.  Once I disable the plugin, preset scrubbing works again.

**System(please complete the following information):**
 - MacOS 10.14.6
 - Lightroom Classic 9.2
 - TangentLightroom 1.3 beta
 - Tangent Wave2 panel

**Comment by crazyscot** [comment]
Hi, thanks for the report. I am having trouble reproducing this with Lightroom Classic 9.2.1 and TangentLightroom 1.3.

I don't really use presets in Lightroom, please can you show me where the control is to scrub through them? I can go into Develop mode, hover over the Presets panel in the Navigator and see the live preview as I hover over different presets - but whatever I do I have not been able to provoke a crash.

**Comment by crazyscot** [comment]
Tangent have now released an official plugin for Lightroom Classic, which works better than mine.
You can get it from [Tangent Support](https://www.tangentwave.co.uk/tangent-support/).
