### ISSUE TITLE
Can't get it to work with Elements - Windows 10

### ISSUE THREAD

**Issue by PhilippFrost** [crazyscot/tangent-lightroom#3]
Installed Python and the plugin into Lightroom Classic

Does the Elements panel need to be mapped using the Tangent Hub? or should it pickup on its own?

Currently no reaction from Elements in LRC

Win10 - 1909

Cheers!

**Comment by crazyscot** [comment]
With the plugin installed the panel ought to pickup automatically, but unfortunately I don't have an Elements panel so it's hard for me to be sure.

Please can you open up Tangent Mapper, select Adobe Lightroom Classic and see whether you get any mappings defined under the Element-Tk page? This will tell me whether the Mapper has found the plugin. I see Shadows, Exposure and Highlights; this screenshot is from OSX but Win10 will look very similar:
![Screen Shot 2020-05-04 at 20 37 13](https://user-images.githubusercontent.com/551990/80948956-34ed2380-8e47-11ea-9912-127089ebff33.png)

**Comment by PhilippFrost** [comment]
Hi again!

So I've tried on a MacOS and it picks up instantly and works, as soon as I add the plugin the Tangent lights up with your mappings.

On Win10, it flashes to "Tangent" text on all panels and thats it. The Tangent Mapper is empty too.

**Comment by PhilippFrost** [comment]
Correction! I've just installed newest version of Tangent Hub 1.6.4 and your plugin 1.3 and it all works!

Thank you so much for this, let me know if I can help you map stuff for Elements!

**Comment by crazyscot** [comment]
Fabulous news, thank you!
You can set up a custom mapping in Tangent Mapper. I don't have a good feel for what works with the Elements. If you do set up a mapping and would like to contribute it, I'll gladly include it in a future release.

**Comment by crazyscot** [comment]
@PhilippFrost You may already know this, but Tangent have just released an official plugin for Lightroom Classic. You can get it from [Tangent Support](https://www.tangentwave.co.uk/tangent-support/).
